name: Deploy to Kubernetes

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: [self-hosted, linux, x64, k3s, lab, bastion]

    env:
      IMAGE_NAME: rubenitos77/nginx-docker-k8s-githubactions
      IMAGE_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up kubectl
        uses: azure/setup-kubectl@v5.1.0
        with:
          version: latest

      - name: Login Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Check cluster access
        run: |
          kubectl config get-contexts
          kubectl config current-context
          kubectl get nodes

      - name: Deploy
        run: kubectl apply -f k8s/

      - name: Verify rollout
        run: |
          kubectl get pods -A
          kubectl get svc -A
